version: "2"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    command: sh -c "ng serve --host=0.0.0.0 --port=4200"
